### PR TITLE
Fix/52 stretched preview

### PR DESCRIPTION
**Pull request by samyakkkk**
PR fixing #52 .

Tested on android & iOS across all resolutions.

### CODE REVIEW

**Review by wilson-christian — APPROVED** [review]

**Comment by vividamazilla** [comment]
Screenshot_20221114-075742

is this the same bug?

**Comment by yipshutak** [comment]
Screenshot_20221114-075742

is this the same bug?

**Comment by Alexd3VAoe** [comment]
i want understand one thing 

Has this problem been fixed ?

You mentioned that the problem will be fixed in two days . its been now 1 month without any changes 

also it mentioned ' To display the preview in full screen, wrap `DeepArPreview` with `Transform.scale()`. ' BUT this is never fix the issue !

**Comment by samyakkkk** [comment]
@Alexd3VAoe `Transform.scale()` is for users who want a full-screen preview and is not related to stretch. We have added `AspectRatio` in the preview itself which fixed the stretched preview problem. Please let us know if it is still not working for you.

**Comment by samyakkkk** [comment]
@yipshutak What you reported is different. Can you please share more details to reproduce it? Thanks.

**Pull request merged**
